Add base plugin - Create table
vladrus13/telegram-bot-ct pull request #4
Opened 2023-07-20 07:54 UTC by MegaVerkruzo

2023-07-20 08:17 UTC, vladrus13 requested changes

2023-07-20 08:17 UTC, vladrus13 commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/PracticePlugin.kt
> +        get() = false
Нужно заменить на обычную инициализаицию, а не на getter

2023-07-20 08:17 UTC, vladrus13 commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/googleapi/GoogleApi.kt
> +
Попробуй вынести общее API в один файл, потому что такое API уже было релизовано

2023-07-20 08:17 UTC, vladrus13 commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/tablemaker/GridRequestMaker.kt
> +            return nToAZ(n / 26 - 1) + (65 + (n % 26)).toChar()
Выглядит формула странно, а еще кажется, задачи по алгоритмам могут легко своим числом превышать 24

2023-07-20 08:17 UTC, vladrus13 commented on telegram-bot-itmo/settings.gradle.kts
> +findProject(":plugins:practiceplugin")?.name = "practiceplugin"
Зачем это?

2023-07-20 08:17 UTC, vladrus13 commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/parsers/neerc/NeercParserInfo.kt
> +            val doc = Jsoup.connect(urlInfo).get()
Тут нужен таймаут

2023-07-20 08:17 UTC, vladrus13 commented on telegram-bot-itmo/skeleton/src/main/kotlin/ru/vladrus13/itmobot/google/GoogleTableResponse.kt
> +        private val SCOPES = listOf(SheetsScopes.SPREADSHEETS, SheetsScopes.DRIVE, SheetsScopes.DRIVE_FILE)
Когда сделаешь класс общий для всех запросов к таблицам, это лучше сделать параметром, потому что не факт, что все запрашиваемые таблички для нас записываемые (например, сейчас это сломает бота)

2023-07-20 08:20 UTC, vladrus13 commented
Так же, пожайлуста, сделай squash некоторых коммитов с истории (да, я этого тоже не делал, но это довольно удобно). Что бы коммиты были целостными

2023-07-20 08:52 UTC, staszw requested changes

2023-07-20 08:52 UTC, staszw commented on telegram-bot-itmo/logger/application_log.txt.1
логи в репозитории не нужны обычно, особенно такие гигантские

2023-07-20 08:52 UTC, staszw commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/Utils.kt
> +class Utils {
Звучит как будто это утилиты для чего-то конкретного

2023-07-20 08:52 UTC, staszw commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/Utils.kt
> +        fun deleteBrackets(str: String) =
brackets это скобки, удаляешь ты не скобки

2023-07-20 08:52 UTC, staszw commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/Utils.kt
> +            // make new list
что за лист? для чего он нужен?

2023-07-20 08:52 UTC, staszw commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/Utils.kt
> +                .update(id, getPrettyRange(title, 0, 1, 2, 2 + listBody[0].size), body)
магические константы?

2023-07-20 08:52 UTC, staszw commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/Utils.kt
> +            val listBody = mutableListOf(mutableListOf("S"))
что такое S?

2023-07-20 08:52 UTC, staszw commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/Utils.kt
> +            val listBody = mutableListOf(mutableListOf("S"))
listOf(mutableListOf("S") + tasks)

2023-07-20 08:52 UTC, staszw commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/Utils.kt
> +            fillInStudents(sheetsService, id, students, title) { ind -> "=Results!B$ind" }
Results используется часто, лучше занести в константу, а не хардкодить каждый раз

2023-07-20 08:52 UTC, staszw commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/Utils.kt
> +                .setValueInputOption("USER_ENTERED")
выглядит как енам

2023-07-20 08:52 UTC, staszw commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/Utils.kt
> +            fillInStudents(sheetsService, id, students, title) { ind -> "=Results!B$ind" }
если хардкодишь колонки, то лучше зафиксируй где-то, какая за что отвечает

2023-07-20 08:52 UTC, staszw commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/parsers/neerc/NeercParserInfo.kt
> +        TODO("Not yet implemented")
?

2023-07-20 08:52 UTC, staszw commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/parsers/neerc/ListChangeDifference.kt
> +    override suspend fun changeTable(id: String) {
не поняла, зачем тебе интерфейс, у которого единственная реализация пустая

2023-07-29 10:31 UTC, MegaVerkruzo commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/Utils.kt
> +            // make new list
[ссылка на гугл таблицу](https://docs.google.com/spreadsheets/d/1VxdwRj2tFrgMK4P_ceQdtg76GLh-d-x_t30KBinINL0/edit#gid=1471883446) - это буквально создание листа)
я с помощью этого метода сгенерил Д1 и Д2

2023-07-29 14:23 UTC, MegaVerkruzo reviewed
Clean code

2023-07-29 14:23 UTC, MegaVerkruzo commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/Utils.kt
> +            val listBody = mutableListOf(mutableListOf("S"))
[Таблица](https://docs.google.com/spreadsheets/d/1VxdwRj2tFrgMK4P_ceQdtg76GLh-d-x_t30KBinINL0/edit#gid=263195973)

Если зайдешь в Д1, то увидишь эту S, - это название колонки, но хорошая идея тоже будет вывести это как константу

2023-07-29 14:23 UTC, MegaVerkruzo commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/Utils.kt
> +                .update(id, getPrettyRange(title, 0, 1, 2, 2 + listBody[0].size), body)
ага)
[таблица](https://docs.google.com/spreadsheets/d/1VxdwRj2tFrgMK4P_ceQdtg76GLh-d-x_t30KBinINL0/edit#gid=263195973) - здесь это положение где - должна быть обновлена таблица
(мне, кстати, идея подсказывает что тут за поля)
![image](https://github.com/vladrus13/telegram-bot-ct/assets/54590439/cb229f4f-6e83-4f09-8268-a159768aa1e5)

2023-07-29 14:23 UTC, MegaVerkruzo commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/Utils.kt
> +                .setValueInputOption("USER_ENTERED")
ну это так, если в будущем захотим отмечать, что это не user сделал (а так захардкожено, вынесу в енамчик)

2023-07-29 14:23 UTC, MegaVerkruzo commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/parsers/neerc/ListChangeDifference.kt
> +    override suspend fun changeTable(id: String) {
Этот интерфейс задал для будущего:
реализация - пустая, потому что еще не приступал к написанию

Мне сейчас надо, чтобы мой парсер мог забирать разницу того, какие новые задания добавили на [link](http://neerc.ifmo.ru/wiki/index.php?title=Список_заданий_по_ДМ_2к_2023_весна)
А если я захочу добавить какой-то другой источник: другой сайт или даже файл, то мне нужно будет по-другому анализировать и выцеплять номера заданий для практики

2023-07-29 14:23 UTC, MegaVerkruzo commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/parsers/neerc/NeercParserInfo.kt
> +        TODO("Not yet implemented")
еще не написал код к этой части (я понял, что нужно было отделить эти коммиты от этого пыра, в след. раз так и сделаю)

2023-07-29 14:23 UTC, MegaVerkruzo commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/tablemaker/GridRequestMaker.kt
> +            return nToAZ(n / 26 - 1) + (65 + (n % 26)).toChar()
https://stackoverflow.com/questions/21229180/convert-column-index-into-corresponding-column-letter

эта штука, позволяет перевести число, например 1 в B или 0 в A или 2 в C или 26 в AA (это необходимо потому мы указываем range !A1:AA1 - например таким образом

2023-07-29 14:23 UTC, MegaVerkruzo commented on telegram-bot-itmo/settings.gradle.kts
> +findProject(":plugins:practiceplugin")?.name = "practiceplugin"
действительно, и правда зачем

2023-07-29 14:23 UTC, MegaVerkruzo commented on telegram-bot-itmo/skeleton/src/main/kotlin/ru/vladrus13/itmobot/google/GoogleTableResponse.kt
> +        private val SCOPES = listOf(SheetsScopes.SPREADSHEETS, SheetsScopes.DRIVE, SheetsScopes.DRIVE_FILE)
аааа, потому что Гошаны таблички недоступны для записи - понял, подумаю над этим

2023-07-31 11:41 UTC, vladrus13 requested changes

2023-07-31 11:41 UTC, vladrus13 commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/AddTable.kt
> +        val parser = NeercParserInfo(id, "http://neerc.ifmo.ru/wiki/index.php?title=Список_заданий_по_ДМ_2к_2023_весна")
Магическая переменная, которая будет меняться. Надо вынести

2023-07-31 13:57 UTC, staszw requested changes

2023-07-31 13:57 UTC, staszw commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/GoogleSheetUtils.kt
очень большой файл, скорее всего его можно разбить на 2-3 поменьше и почитаемее

2023-07-31 13:57 UTC, staszw commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/AddTable.kt
> +//        val list = GoogleSheetUtils.getTasksList(sheetsService, id);
либо в дебаг логи унеси, либо удали

2023-07-31 13:57 UTC, staszw commented on telegram-bot-itmo/README.md
> +### What you may fix?
думаю это можно сделать отдельным мром и быстреньком вмерджить

2023-07-31 13:57 UTC, staszw commented on telegram-bot-itmo/.gitignore
> +logger/application_log.txt.*
logger/*?

2023-07-31 13:57 UTC, staszw commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/Utils.kt
> +            // make new list
лист это по-русски, по-английски это sheet получается

2023-07-31 13:57 UTC, staszw commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/GoogleSheetUtils.kt
> +                                            .setType(INTERPOLATION_POINT_TYPE_MIN)
гигантская вложенность

2023-07-31 13:57 UTC, staszw commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/GoogleSheetUtils.kt
> +                    // up
если все-таки добавляешь комментарии, то хочется чтобы было понятно что они значат

2023-07-31 13:57 UTC, staszw commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/GoogleSheetUtils.kt
> +        private fun getRussianT() = 'Т'
тебе нужна же не буквально буква, она что-то значит

2023-07-31 13:57 UTC, staszw commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/GoogleSheetUtils.kt
> +         * @param title is "Д[0-9]+" or MAIN_LIST_NAME
в джавадоках можно ссылать на переменные, лучше так и сделать в кейсе с MAIN_LIST_NAME

2023-07-31 13:57 UTC, staszw commented on telegram-bot-itmo/settings.gradle.kts
> +include("plugins:tempplugin")
tempplugin кажется не существует

2023-07-31 15:39 UTC, MegaVerkruzo commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/Utils.kt
> +            // make new list
))))))

2023-08-07 19:25 UTC, MegaVerkruzo commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/AddTable.kt
> +        val parser = NeercParserInfo(id, "http://neerc.ifmo.ru/wiki/index.php?title=Список_заданий_по_ДМ_2к_2023_весна")
этот пыр позже чекнем

2023-08-07 19:25 UTC, MegaVerkruzo commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/GoogleSheetUtils.kt
факт, но сначала как я понял надо предыдущий пыр добить, а потом уже переходить к следующему

2023-08-07 19:30 UTC, MegaVerkruzo commented on telegram-bot-itmo/plugins/practiceplugin/src/main/kotlin/ru/vladrus13/itmobot/plugin/practice/GoogleSheetUtils.kt
> +        private fun getRussianT() = 'Т'
мне нужна буквально буква - потому что делаю табличку по аналогу с [актуальной](https://docs.google.com/spreadsheets/d/17PtqM8ghzsGhRqlfDa2rAhLxVJ0mvXr3eQCygmFsHRA/edit#gid=1762486287)

2023-08-07 19:45 UTC, MegaVerkruzo commented
Ну, я убрал в отдельную ветку все новвоведения, хочу убедиться, что в текущем варианте - все оке и тогда продолжу далее

2023-08-08 07:48 UTC, vladrus13 approved these changes

2023-08-09 12:01 UTC, merged